#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

IMAGE_NAME="vnpt-ai:latest"
TEST_DATA_DIR="$PROJECT_ROOT/test_data"
OUTPUT_DIR="$PROJECT_ROOT/test_output"

mkdir -p "$TEST_DATA_DIR" "$OUTPUT_DIR"

echo "Running Docker with VNPT API Mock..."

docker run \
    --rm \
    -v "$TEST_DATA_DIR:/data:ro" \
    -v "$OUTPUT_DIR:/output" \
    -e VNPT_LARGE_AUTHORIZATION="$VNPT_LARGE_AUTHORIZATION" \
    -e VNPT_LARGE_TOKEN_ID="$VNPT_LARGE_TOKEN_ID" \
    -e VNPT_LARGE_TOKEN_KEY="$VNPT_LARGE_TOKEN_KEY" \
    -e VNPT_SMALL_AUTHORIZATION="$VNPT_SMALL_AUTHORIZATION" \
    -e VNPT_SMALL_TOKEN_ID="$VNPT_SMALL_TOKEN_ID" \
    -e VNPT_SMALL_TOKEN_KEY="$VNPT_SMALL_TOKEN_KEY" \
    -e VNPT_EMBEDDING_AUTHORIZATION="$VNPT_EMBEDDING_AUTHORIZATION" \
    -e VNPT_EMBEDDING_TOKEN_ID="$VNPT_EMBEDDING_TOKEN_ID" \
    -e VNPT_EMBEDDING_TOKEN_KEY="$VNPT_EMBEDDING_TOKEN_KEY" \
    "$IMAGE_NAME"